### ISSUE TITLE
Installer creating empty 'git' file

### ISSUE THREAD

**Issue by LuciousLisa** [ThorsCrafter/Reactor-and-Turbine-control-program#29]
The installer seemed to be broken for me. The `pastebin get HMtbgkwt git` command should create the 'git' file with which to import the code on the pastebin. However, it created an empty 'git' file in my case.

After copying and pasting the content of the pastebin into the actual file on my actual computer (/home/lisa/ftb/SpaceAstronomy/minecraft/saves/New World/computer/1/git) I was able to execute the 'git' file and now the program is running smoothly.

Some (hopefully) helpful data:
I'm running Minecraft 1.7.10
My machine runs on Debian Linux
The version of Computercraft I'm running is 1.7

Let me know if there's any additional info that you need to help resolve the issue.

**Comment by ThorsCrafter** [comment]
As far as I know there are problems with pastebin at the moment, because they switch from http to https, so that you can't download programs with the usual pastebin way. I don't know if that's exactly what happened to you, because you do get the git program apparently (even if it is empty). You can try using the following workaround for pastebin. Please tell me if this fixes your problem. If not, I have to look into this more deeply.

- Copy the original pastebin file to a new one: `cp /rom/programs/http/pastebin pastebinpatch`
- Then edit the new file with `edit pastebinpatch`
- Find the two lines containing the pastebin links and replace http://pastebin.com with https://pastebin.com
- Save the file and exit it.
- After this you should be able to download files as usual, but using `pastebinpatch get <code> <name>`.

I hope this helps.
Thor_s_Crafter

**Comment by LuciousLisa** [comment]
Unfortunately that workaround did not resolve the issue.

Copying went fine, editing the file went fine, finding and replacing the http(s) went fine, but after saving it and running it to create 'git2', it still didn't create any content in that file.

Looks like it requires more work for you, I'm sorry. :disappointed: 

Feel free to involve me again, I'd be happy to help test some more. :smiley:

**Comment by ThorsCrafter** [comment]
Ok. If that's the case, I have to test this by myself and try to figure out what is happening here. Thanks for the report anyway.

**Comment by ThorsCrafter** [comment]
One more question. Which version do you use (release or beta?)

**Comment by LuciousLisa** [comment]
I'm using release, version 2.5.

**Comment by ThorsCrafter** [comment]
After doing some testing and searching on Google (and asking some other people) I figured out, that this is definitly a bug of ComputerCraft/Pastebin. Hence, I can't do anything about it (unfortunately).
