### ISSUE TITLE
Language rework

### ISSUE THREAD

**Issue by ThorsCrafter** [ThorsCrafter/Reactor-and-Turbine-control-program#30]
- [ ] Create a language txt file to store the language text files
- [ ] Create a table with variables containing text phrases

**Comment by Bjonnfesk** [comment]
I suggest that we write the language file in JSON instead of as a flat text file, which will essentially create the table in the **file** instead of in the program. This means that if support for more languages is added at a future time, the _code_ will not need to be modified, only the language file.
