### ISSUE TITLE
Rod depth control

### ISSUE THREAD

**Issue by Vecingettorix** [ThorsCrafter/Reactor-and-Turbine-control-program#35]
Hi. Love the program.

One issue I have been having is that the program sets the control rods too low, and won't move them (if i manually do it, the program resets them). This results in too little steam, so it disengages the coils to speed up, only to have to stop them again almost as soon as they have been re-engaged.
Is this a problem I can fix in my setup?
Currently have max size turbines fed from an (excessively) big reactor.

I am not worried about the fuel consumption, but the power generation is too unreliable since it constantly switched them all on/off constantly.

Thanks!

**Comment by ThorsCrafter** [comment]
I know, that the program has problems with "too efficient" reactors.
Unfortunately, I haven't figured out, how to fix this.
I plan to do an option for this, so that you can set the fuel rods as you like. 
Sometimes, deleting the config and letting it recalculate helps. If that doesn't help, you can manually edit the rods inside the options.txt file, located in your computer here: **/reactor-turbine-program/config/options.txt**. (or on Github: https://github.com/ThorsCrafter/Reactor-and-Turbine-control-program/blob/master/turbineControl_v2/src/config/options.txt) for now.
Just edit the line ` rodLevel = 0,`  to a value you want.

**Comment by Vecingettorix** [comment]
Awesome I will give this a go!
Thanks :)

**Comment by Vecingettorix** [comment]
I wasn't sure if a response would be any use to you but jsut in case;

I deleted the config which seemed to crash the system (reactor off, coils locked on losing speed).
After rebooting, the rod depth is still the same, however the reactor is now comfortably producing enough steam so I am not really sure what is going on.

Thankyou for your help anyway!
