### ISSUE TITLE
Touchpoint:142: Fehler

### ISSUE THREAD

**Issue by la1998** [ThorsCrafter/Reactor-and-Turbine-control-program#46]
Hey ich brauchte mal deine Hilfe wen ich alles installiere und der Computer dann Rebooten kommt dann
remoteVer: 2.6
localVer: 2.6-release
Update? -> false
touchpoint :142: attempt to index ? (a nil value) 

Ich wäre dir sehr dankbar wen du eine Lösung hättest

**Comment by la1998** [comment]
das wäre ja in der config die Touchpoint.lua und die Zeile 142:
self.buttonList[name].label, newName = setupLabel(self.buttonList[name].xMax - self.buttonList[name].xMin + 1, self.buttonList[name].yMin, self.buttonList[name].yMax, newName)

ich bin nicht so der experte in computercraft verstehe nur wenig davon. aber ich sehe hier kennen Fehler und glaube in der richtigen Datei nachgeschaut zuhaben

**Comment by ThorsCrafter** [comment]
Hallo la1998,
das ist offensichtlich ein Fehler bei der Interaktion von der touchpoint API (die meine ganzen Buttons steuert) mit meinem Programm. Warum der Fehler bei dir auftritt, kann ich allerdings so nicht sagen, dazu brauche ich mehr Informationen zu deinem Aufbau.
Außerdem schreibe hier bitte nur in Englisch, das ist in Github so üblich oder schreibe alternativ in meinem Forum (forum.thorscrafter.de) oder mir per Email (mail@thorscrafter.de).

--------------

Hello la1998,
your problem is obviously one between the interaction of the touchpoint API (which handles all of my buttons) and my program itself. For which reasons the error shows up in your case, I can't tell without some more informations about your setup.
Please write in English only here on Github. You can write me in German in my Forum (forum.thorscrafter.de) or via Email (mail@thorscrafter.de)

**Comment by la1998** [comment]
hey oh sorry. okey i have send you a e-mail

**Comment by Tejasminer** [comment]
I am having the same error. I have an extreme reactor with 4 turbines. Touchpoint:142: attempt to index ? (a nil value) It is on a public server if you would like to see it.

**Comment by Tejasminer** [comment]
i am using an advanced computer, advanced monitors with a 4 x 7 display area. Modems are connected to each turbine and the reactor. The computer is next to the monitors touching so no cable or modem. All modems are active.

**Comment by Tejasminer** [comment]
I have tried the beta version as well on another reactor with one turbine and the same issue.

**Comment by N7Tempest** [comment]
Sorry if this is long overdue, but I had this same issue, and discovered a fix for me. In the menu.lua file, it is trying to reference the language setting, which is set to "nil" at that point. I was able to get past that error by adding the following line at the top of the code:

lang = "en" 

I also had to modify the yMin and yMax for the "Restart" button because it was "Out of Bounds" at 20. I dropped it to 18, and dropped the previous buttons a little too in order to prevent "Overlapping".

Now I am stuck on another issue. The menu loads on the computer and crashes back to a terminal prompt. Nothing on the monitor. Still looking into that one.

**Comment by ThorsCrafter** [comment]
> The menu loads on the computer and crashes back to a terminal prompt.

Do you get any error messages in the terminal?

**Comment by N7Tempest** [comment]
No, which makes going from there difficult. My guess is that it has something to do with the monitor since the menu loads on the computer, not on the monitor. The menu doesn't even clear off when it crashes out. The terminal cursor is in the middle of the screen and nothing above it is readable due to the menu seemingly covering it. 
 I have pretty much given up on it now though since I saw your closed ticket about my same original issue being compatibility with newer CC and Minecraft versions. Each bug corrected just opened up another to figure out. I still couldn't even get the modem to connect to any energy storage I tried. So I'll await the new 3.0 program. I hope that is coming along well for you.

**Comment by CryneOnGithub** [comment]
Same problem here

**Comment by TheArchitectIO** [comment]
Hello, i have started to fix this project over at https://gitlab.com/seekerscomputercraft/extremereactorcontrol/

I have the current 2.6 version working again (only english looking into multiple language options)

Test with 20 Turbines + 1 Reactor and 2 standalone reactors

**Comment by ThorsCrafter** [comment]
Hey @TheArchitectIO, that's great! If you want, I can edit the Readme of this repository to link to your (new) Gitlab project.

**Comment by TheArchitectIO** [comment]
> Hey @TheArchitectIO, that's great! If you want, I can edit the Readme of this repository to link to your (new) Gitlab project.

Hello Thor, If you would do that it would be awesome, working on getting everything back to 100% today so i can knock out any outstanding issues and start work on a code restructure for a v3 and better language support

**Comment by ThorsCrafter** [comment]
Alright. That's done :)
I will archive this repository, if you need anything else from me, please contact me via my new profile: https://github.com/sthorsten
