### ISSUE TITLE
cannot start program

### ISSUE THREAD

**Issue by Rosentti** [ThorsCrafter/Reactor-and-Turbine-control-program#47]
### When i try to start the program i get this:

> touchpoint:142: attempt to index ? (a nil value)

i have tried reinstalling the program, but to no avail.
Minecraft version: 1.12.2
Program Version: 2.6-release
computercraft version: 1.80.pr1
erroring line contains this text: 

> self.buttonList[name].label, newName = setupLabel(self.buttonList[name].xMax self.buttonList[name].xMin + 1, self.buttonList[name].yMin, self.buttonList[name].yMax, newName)

**Comment by ThorsCrafter** [comment]
The program is currently designed to work with Computercraft 1.7 (which is Minecraft 1.7.10).
Newer versions are currently not supported (yet!). Since I am working on version 3.0 anyways (you can have a look at the [feature/code-restructuring](https://github.com/ThorsCrafter/Reactor-and-Turbine-control-program/tree/feature/code_restructuring) branch), I won't port this version (2.6) to the newer ComputerCraft version. Additionally, ComputerCraft for this version is still in Beta anyways.

**Comment by Rosentti** [comment]
ok, thanks
