### ISSUE TITLE
Rotor Speed not displaying in Auto mode (v2.6)

### ISSUE THREAD

**Issue by Lorestiel** [ThorsCrafter/Reactor-and-Turbine-control-program#48]
This is due to a typo on lines 903, 908 (and carried forward to 913) in turbinecontrol.lua, the cursor is set to line 15 to write rotor speed, and a second time to write the energy buffer, overwriting the Rotor Speed.

![image](https://user-images.githubusercontent.com/40328193/41503989-7f8247ea-71d9-11e8-9fc4-60b8301592bf.png)

p.s. many thanks for this excellent project.

**Comment by ThorsCrafter** [comment]
Thanks for your feedback! I think you are one of the few people actually having a look at the code (especially since it is line 903 and forward). Since I currently work on version 3.0 which is a complete rebuild from scratch essentially, this doesn't get fixed though. You can have a look at the [feature/code_restructuring](https://github.com/ThorsCrafter/Reactor-and-Turbine-control-program/tree/feature/code_restructuring) branch if you want.
