### ISSUE TITLE
Turbine RPM going past maximum set.

### ISSUE THREAD

**Issue by ApolloHusky** [ThorsCrafter/Reactor-and-Turbine-control-program#52]
I have one reactor and two turbines running off of it. And with automatic control with your program, it works well, but the turbines RPM continues to climb way past 1820 unless I stop it and slow them down. You should add a function to detect the turbines RPM and if its past 1820 it should shut down the turbines and/or reactor to slow them down and keep them around 1800 RPM

**Comment by Bjonnfesk** [comment]
Definitely shut down the _reactor_, not the turbines, as shutting down the turbines would lead to overheating the reactor.

I will attempt to quickly fix this issue and add it to my pull request for #50, but as that pull request has already existed for more than a year with no response from @ThorsCrafter @sthorsten, I am not very hopeful about it being accepted.

**Comment by Bjonnfesk** [comment]
I don't have a computer, nor a BigReactors setup to test, but I suspect [allAtTargetSpeed(), line 634, turbineControl.lua](https://github.com/ThorsCrafter/Reactor-and-Turbine-control-program/blob/d2577699ab923dec91152188ad2fc59c8a34ea19/turbineControl_v2/src/program/turbineControl.lua#L634) might be the culprit. It seems rather naïve, as it only returns true (ie. the program will stop spinning up the turbines) if _all_ turbines are at maximum speed, a strategy which assumes that all turbines are exactly the same. Let me ask you a few questions to see if this is likely to be the problem:

- When does the turbine overspeed occur? Is it while the turbines are spinning up (before the coils are engaged), or after the turbines have spun up, the coils are engaged and power production has begun? If the latter, then your turbines are out of spec as per the BigReactors/ExtremeReactors rules; you should not be using a turbine that can spin faster than about 1800 RPM with the coils engaged. Nonetheless, the program should _at least_ give you a message telling you to redesign your turbines. It should also (perhaps optionally...?) scram the reactor immediately, as a turbine overspeed would certainly cause a turbine trip and normally a consequent reactor trip in the real world ([source](https://www.nuclear-power.net/nuclear-power-plant/turbine-generator-power-conversion-system/what-is-steam-turbine-description-and-characteristics/turbine-trip/)).
- What is the last message displayed on screen before the turbine overspeeds (if the overspeed happens while spinning up)? (Not sure if I remember correctly how this program works, apologies if this is completely off the mark)
- What are the precise specifications of your turbines and your reactor? Steam mb\t, reactor dimensions, turbine dimensions, number and material of coils, number of blades, etc.
- Are all your turbines identical?

If the problem is that your turbine overspeeds _after_ power generation has begun, then I rather think the problematic code is located at [startAutoMode(), line 113, turbineControl.lua](https://github.com/ThorsCrafter/Reactor-and-Turbine-control-program/blob/d2577699ab923dec91152188ad2fc59c8a34ea19/turbineControl_v2/src/program/turbineControl.lua#L113). This line seems to encourage overspeeding the turbines. It and the following lines, should read something along the lines of:

```lua
local turbineTripSpeed = turbineTargetSpeed * 1.05 -- set the speed at which the turbine trips to 105% of the target speed; this is a conservative number, but this is nuclear safety we're dealing with
if tSpeed >= turbineTripSpeed then -- turbine is overspeeding; turbine trip, reactor trip
   mon.setTextColor(colors.red) -- set the text colour to red so the user knows it's serious. This is NOT a drill.
   mon.write("Turbine trip: overspeed!") -- warn the user
   allTurbinesOff() -- disables all turbines (hopefully)
   r.setActive(false) -- disables the reactor (if we can call this from here, God knows where r is defined)
elseif ((tSpeed >= turbineTargetSpeed) and (tSpeed < turbineTripSpeed)) -- check again if we're overspeeding, for good measure
   mon.setTextColor(colors.green)
   mon.write(" OK  ")
else
   mon.setTextColor(colors.red)
   mon.write(" ...  ")
end
```

Furthermore, as it appears that the main loop of the program resides in [clickEvent(), line 735, turbineControl.lua](https://github.com/ThorsCrafter/Reactor-and-Turbine-control-program/blob/d2577699ab923dec91152188ad2fc59c8a34ea19/turbineControl_v2/src/program/turbineControl.lua#L735), this loop should also check if the turbine is currently overspeeding (`if tSpeed >= turbineTripSpeed`), and if it is, perform the same sequence of actions as the above code does.

If I can find the time, I will test out these changes and add them to my aforementioned pull request. Even if the pull request is not accepted by @sthorsten, you will still be able to download the fixed version from _my_ GitHub.
